---
title: "Academic Honesty"
---

Learning thrives in an environment built on trust and respect. The subsequent actions undermine academic integrity, creating obstacles to effective learning:

- Allocating less time than necessary for a satisfactory job.
- Skipping readings or neglecting non-graded activities.
- clicking through course information without thoroughly reviewing resources.

While these behaviors can impact your grade and learning experience, they are personal choices. On the other hand, certain actions go beyond mere 'choices' and breach academic regulations and even legal boundaries. These include:

- Plagiarizing text by directly copying from websites, blogs, other discussions, or published texts.
- Recycling an essay or project previously submitted for another class.
- Engaging in dishonest practices during a test or project.
- Copying directly from another student or source without proper attribution.
- Purchasing or replicating an essay or project from an online source.

It's crucial to familiarize yourself with the Cal Poly definitions of <a href="https://academicprograms.calpoly.edu/content/academicpolicies/Cheating" target="_blank">Cheating and Plagiarism.</a> Take a moment to read this page and understand these concepts.

If you're uncertain about citing a source, incorporating a quote, or acknowledging someone in your summaries, I'm here to assist. We can arrange a brief Zoom or in-person meeting, or I can provide feedback on a draft. Writing rules can be confusing; let's clarify them together!

On the downside, the college doesn't differentiate between breaking rules intentionally or unintentionally—the consequences remain consistent. In my class, the first instance of misquoting, misrepresentation, or copy/pasting requires a redo of the work and a one-on-one meeting with me. Upon a second occurrence, we meet again, but you won't be allowed to redo the assignment, receiving a zero for that grade. For a third instance, you will not pass the class. Let's take a proactive approach! If you're unsure about citing, don't hesitate to ask!