---
toc: true
---

## Accessibility, Diversity and Inclusion

This course was designed to serve students from all diverse backgrounds, places, and perspectives, in order to meet your needs. I view the diversity that participants bring to this classroom as a resource, strength, and benefit. It is my intent to present materials and activities that are respectful of gender, sexuality, disability, age, socioeconomic status, ethnicity, race, religion, country of origin, and culture. I encourage and appreciate your feedback and suggestions. Please let me know if there are ways I can improve the effectiveness or experience of this class for you. In addition, if any of the assignment dates conflict with your religious events, please let me know so that we can make arrangements for you.

I have taken numerous steps to ensure that all of the materials presented in this course are accessible to all participants, regardless of physical or learning disabilities. I know that everyone is unique, and I may have unintentionally overlooked something that limits access to some materials or activities. Please let me know if you cannot access any content. If you find you need additional accommodations to complete the required course work, please contact me via email (<a href = "mailto:sdemirci@calpoly.edu" target="_blank">sdemirci@calpoly.edu</a>) or come to my office! You can also contact the Disability Resource Center, Building 124, Room 119, at (805) 756-1395. 

[SensusAccess](https://lib.calpoly.edu/study-spaces-and-tech/convert/) is a self-service, alternate media solution made available by Kennedy Library to automatically convert files into a range of alternate media including audio books (MP3 and DAISY), e-books (EPUB, EPUB3 and Mobi) and digital Braille. The service can also be used to convert inaccessible files such as image-only PDF files, JPG pictures and Microsoft PowerPoint presentations into more accessible and less tricky formats. This service is available at no charge for all Cal Poly students, faculty, staff and alumni. Also, starting Summer 2021, alternative formats within Canvas have been enabled with Ally. [Learn more about Ally's alternative formats.](https://canvassupport.calpoly.edu/ally-students)

## Disability Accomodations

This course was developed with accessibility in mind; however, if you require accommodations or assistance of any kind, or cannot access materials in the course, or complete an assignment due to a disability, please contact me via email (<a href = "mailto:sdemirci@calpoly.edu" target="_blank">sdemirci@calpoly.edu</a>) or come to my office as soon as you can, so I can assist you promptly. 

I want to support your success. If you wish to request disability-related accommodations for this or any other course, please contact the <a href = "https://drc.calpoly.edu/content/drc-services" target="_blank">Disability Resource Center</a>. It's important to do this with as much advanced notice as possible, so you have full access to your course materials and activities in a timely manner.