---
title: "Student Support and Basic Needs"
toc: true
---

## Technical Assistance
For technical questions, such as the suitability of your home computer for the course, installing plug-ins, problems with your password, etc., contact the CalPoly Help Desk at phone: 805-756-7000 or email: <a href = "mailto:sservicedesk@calpoly.edu">servicedesk@calpoly.edu</a> 



## Student Support and Basic Needs

Are you...

- Having difficulty affording groceries or accessing sufficient food to eat?  
- Lacking a safe and stable place to live? 
- Needing additional essential supports? 


If so, you’re not alone and there are campus resources available to help. At Cal Poly, we want to ensure that all students have their basic needs met, including food, shelter, and clothing.  Explore these pages to find out more and get connected:  

[Food Hub](https://basicneeds.calpoly.edu/food-resources) – Access to free food (Cal Poly Food Pantry) or reduced-cost food and hot meals (Meal Vouchers and Cal Fresh)   
[Financial Resources](https://basicneeds.calpoly.edu/financial-resources) – Cal Poly Cares & The Professional Clothing Closet  
[Housing & Community Resources](https://basicneeds.calpoly.edu/community-resources) - On and Off-Campus Housing & Transportation    
[Mental Health & Academic Support](https://basicneeds.calpoly.edu/mental-health-resources) - Counseling, academics, & disability accommodations   

Reach out to the [Dean of Students Office](mailto:deanofstudents@calpoly.edu) if you need help navigating these resources, or if your concern is not listed here. 

### Mental Health 

Wherever you are on your academic and personal journey, [Counseling Services](https://chw.calpoly.edu/counseling) is here to help you take steps toward emotional health and wellbeing through Cal Poly's clinical, educational, and consultative services. 

Getting started just takes one call to (805) 756-2511. You’ll be scheduled for a brief screening appointment over the phone to talk about what you’re experiencing and discuss what services will best meet your needs.Your provider may suggest [group therapy](https://chw.calpoly.edu/counseling/group-therapy), a [workshop](https://chw.calpoly.edu/counseling/emotional-wellbeing-workshops), [individual counseling](https://chw.calpoly.edu/counseling/individual-therapy), or a [referral](https://chw.calpoly.edu/counseling/community-referrals) to a community therapist covered by your insurance. Counseling Services focuses on providing brief treatment for students. There are no set session limits - this gives us the flexibility to make collaborative decisions considering both your clinical needs and the resources available to you.   

If you’re in [crisis](https://chw.calpoly.edu/counseling/crisis-and-triage-services), or need to talk to someone right away, call (805) 756-2511 any time of day. They also have same-day sessions available for students in distress to meet with a counselor. 

And if you’re not sure you’re ready for counseling, you may want to drop in to [Let’s Talk](https://chw.calpoly.edu/counseling/lets-talk). This is informal consultation with providers to discuss a concern, find a solution to a problem, or talk about a situation you’re feeling stuck in.  No appointment needed, and no notes are taken. The schedule of times and locations for each of the Let’s Talk sessions can be found [online](https://chw.calpoly.edu/counseling/lets-talk). 

[The team](https://chw.calpoly.edu/counseling/counseling-staff) is invested in providing culturally-responsive care, promoting belonging and inclusion, and cultivating relationships with students, faculty, and staff on campus to build bridges to care, making access to mental health care more equitable. [Reach out](mailto:counseling@calpoly.edu) to us if you have any questions! 

### Student Support Services
Below you will find a full list of Student Support Services at Cal Poly. I encourage each of you to explore the services that will best meet your needs:

[Academic Advising](https://advising.calpoly.edu/)   
[Cal Fresh: Financial Aid for Food](https://www.calfreshcalpoly.org/)   
[Career Services](https://careerservices.calpoly.edu/)   
[Center for Military Connected Students](https://militaryconnected.calpoly.edu/)   
[Dean of Students Office](https://deanofstudents.calpoly.edu/)   
[Disability Resource Center](https://drc.calpoly.edu/)   
[Dream Center](https://dreamcenter.calpoly.edu/)   
[Financial Aid and Scholarships](https://www.calpoly.edu/financial-aid)   
[Food Pantry](https://basicneeds.calpoly.edu/foodpantry)   
[Gender Equity Center](https://culture.calpoly.edu/GenderEquity)   
[Getting Good Grades with Gadgets](https://drc.calpoly.edu/content/getting-good-grades-gadgets)   
[Campus Health and Wellbeing](https://chw.calpoly.edu/)   
[Multicultural Center](https://culture.calpoly.edu/MultiCultural)   
[Mustang Success Center](https://success.calpoly.edu/)   
[Pride Center](https://culture.calpoly.edu/PrideCenter)   
[Safer](https://safer.calpoly.edu/)   
[Transfer Center](https://transfercenter.calpoly.edu/)   
[Tutoring Resources and Supplemental Workshops ](https://advising.calpoly.edu/tutoring-study-sessions-and-workshops)   
[Writing Center](https://calpoly.mywconline.com/)
