---
toc: true
---

## Course Content

The course content, available here, is further enriched by in-class presentations and activities. Each week, we'll engage with the material through:

- Reading assignments introducing key concepts for the unit/topic.
- Followed by lectures, in-class activities, or lab sessions exploring the week's content.
- Submitting _weekly assignments_ through [__Canvas__](https://canvas.calpoly.edu/).

## Weekly Layout

Discover the Weekly Layout — a comprehensive guide to your week's agenda. Access 

lecture slides <i class="fas fa-file-lines"></i>,  
videos <i class="fas fa-video"></i>,    
reading materials <i class="fas fa-book-open"></i>,  
weekly assignments <i class="fas fa-user"></i> <i class="fas fa-upload"></i>,  
group assignments <i class="fas fa-users"></i> <i class="fas fa-upload"></i> and  
due dates <i class="fas fa-clock"> </i>,  

all conveniently organized for your academic journey.


### {{< fa calendar-days >}} Week 1 (Jan 8 - Jan 11)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 33%">BEFORE CLASS</th>
    <th style="width: 37%">DURING CLASS</th>
    <th style="width: 30%">AFTER CLASS</th>
  </thead>

  <tr>
    <td>&nbsp; Nothing, just come to the class!</td>
    <td>
      &nbsp;<input type="checkbox" /><a href="https://stat218-wi24.github.io/slides/01-Week-01/01-welcome.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Covering the website & syllabus</a> <i class="fas fa-file-lines"></i>   
      &nbsp;<input type="checkbox" /> A Discussion on Life Science and Statistics <i class="fas fa-comments"></i>   
      &nbsp; &nbsp;<input type="checkbox" /> Watching short videos <i class="fas fa-video"></i>   
      &nbsp;&nbsp;&nbsp; <a href="https://www.youtube.com/watch?v=Tm2cCnRjcOM&list=PLkIselvEzpM5nFf4nu--q2OGccA_0alYO" target="_blank">
        <i aria-hidden="true" title="External Link to YouTube"></i> 1. Using data to better understand agriculture.</a>   
      &nbsp;&nbsp;&nbsp;<a href="https://www.youtube.com/watch?v=Bz0e5xGDHaU&list=PLkIselvEzpM5nFf4nu--q2OGccA_0alYO" target="_blank">
        <i aria-hidden="true" title="External Link to YouTube"></i> 2. Using statistics to treat chronic illnesses.</a>
  </td>

  <td> 
       &nbsp;<input type="checkbox" /> <a href="https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen" target="_blank"> <i aria-hidden="true" title="External Link to YouTube"></i> The best stats you've ever seen</a> <i class="fas fa-video"></i>  
      &nbsp;<input type="checkbox" /> Group Formation <i class="fas fa-users"></i>  
      &nbsp;<input type="checkbox" /> <b> Week 1 Assignment </b><i class="fas fa-user"></i> <i class="fas fa-upload"></i>     
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A short paragraph on the life science &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and statistics    
<br>
<i class="fas fa-clock"></i><b> DUE DATE: Sun, Jan 14 </b>
  </td>
</tr>

  <tr>
    <td> &nbsp; <b> CH 1: Introduction </b>  
    &nbsp;<input type="checkbox" /> <b>Section 1.2:</b> Types of Evidence <i class="fas fa-book-open"></i>    
&nbsp; FROM Samuels et al. (2016)</td>
    <td>    
    &nbsp; <input type="checkbox" /> <a href = "https://stat218-wi24.github.io/slides/01-Week-01/02-Week-1-Lec-02.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slides"></i> Lecture Slides - Types of Evidence </a>&nbsp;<i class="fas fa-file-lines"></i>   
    &nbsp; <input type="checkbox" /> Guided Classroom Activity <i class="fas fa-comments"></i>   
    </td>
    <td>
    &nbsp;<input type="checkbox" /> <b> Week 1 Assignment </b><i class="fas fa-user"></i> <i class="fas fa-upload"></i>  
    &nbsp; &nbsp;&nbsp;&nbsp; Exercises 1.2.2; 1.2.4; and 1.2.6    
<br>
<i class="fas fa-clock"></i>  <b> DUE DATE: Sun, Jan 14 </b>
</td>
  </tr>

  <tr>
    <td> &nbsp; <b> CH 1: Introduction </b>  
    &nbsp;<input type="checkbox" /> <b>Section 1.3:</b> Random Sampling <i class="fas fa-book-open"></i>    
&nbsp; FROM Samuels et al. (2016)</td>
    <td>
    &nbsp; <input type="checkbox" /> <a href = "https://stat218-wi24.github.io/slides/01-Week-01/03-Week-1-Lec-03.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slides"></i> Lecture Slides - Random Sampling </a>&nbsp;<i class="fas fa-file-lines"></i>      
    &nbsp; <input type="checkbox" /> Guided Classroom Activity <i class="fas fa-comments"></i>   
    </td>
    <td>
    &nbsp;<input type="checkbox" /> <b> Week 1 Assignment </b><i class="fas fa-user"></i> <i class="fas fa-upload"></i>  
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Exercises 1.3.3    
<br>
<i class="fas fa-clock"></i><b> DUE DATE: Sun, Jan 14 </b>
    </td>
  </tr>

  <tr>
    <td>
      &nbsp; <b> Introduction to R and RStudio – Lab 1</b>  
      &nbsp; <input type="checkbox" /><a href = "https://cran.rstudio.com/" target = blank> Install R</a> <i class="fas fa-download"></i>     
      &nbsp; <input type="checkbox" /> <a href = "https://posit.co/download/rstudio-desktop/" target = blank>Install RStudio</a> <i class="fas fa-download"></i>  
    </td>
    <td>    
    &nbsp; <input type="checkbox" /> <a href = "https://stat218-wi24.github.io/slides/01-Week-01/04-Week-1-Lec-04-Lab-01.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lab Slides - Hello R! </a>&nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    <td> &nbsp; <input type="checkbox" /> Review the lab session materials <b>(No submission for this lab)</b>
    </td>
  </tr>

</table>



### {{< fa calendar-days >}} Week 2 (Jan 15 - Jan 18)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 35%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

<tr>
  <td colspan="3" style="text-align: center;">&nbsp; <b>No Class Today !</b></td>
</tr>

  <tr>
    <td> &nbsp; <b> Ch 2: Description of Samples and Populations </b>  
    &nbsp;<input type="checkbox" /> <b>Section 2.1:</b> Introduction to Variables <i class="fas fa-book-open"></i>    
    &nbsp;<input type="checkbox" /> <b>Section 2.2:</b> Frequency Distributions <i class="fas fa-book-open"></i>  
&nbsp; FROM Samuels et al. (2016)</td>
    <td>    
    &nbsp; <input type="checkbox" /> <a href = "https://stat218-wi24.github.io/slides/02-Week-02/01-Lecture-01/01-Week-02-Lec-01.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Variables and Frequency Distributions </a>&nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    
  <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercises 2.1.1; 2.2.6   
<br>
<i class="fas fa-clock"></i>  <b> DUE DATE: Sun, Jan 21 </b>
</td>
  </tr>

  <tr>
  <td> &nbsp; <b> Introduction to Quarto – Lab 2</b> </td>
    <td>    
    &nbsp; <input type="checkbox" /> Review 1 - Quiz (On Canvas)</a> &nbsp; <i class="fas fa-highlighter"></i>   
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/02-Week-02/02-Lecture-02/01-Week-02-Lec-02-Lab-02.html#/title-slide" target="_blank"><i aria-hidden="true" title="External Link to Lab Slides"></i> Lab Slides - Hello Quarto!</a>&nbsp; <i class="fas fa-file-lines"></i>       
    <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Lab Assignment 1   
<br>
<i class="fas fa-clock"></i>  <b> DUE DATE: Sun, Jan 21 </b>
</td>
  </tr>

  <tr>
    <td> &nbsp; <b> Ch 2: Description of Samples and Populations </b>  
    &nbsp;<input type="checkbox" /> <b>Section 2.3:</b> Descriptive Statistics <i class="fas fa-book-open"></i>    
    &nbsp; FROM Samuels et al. (2016)</td>
    <td>
     &nbsp; <input type="checkbox" /> <a href = "https://stat218-wi24.github.io/slides/02-Week-02/03-Lecture-03/01-Week-02-Lec-03.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Shapes, Center and Spread of a Distribution </a>&nbsp; <i class="fas fa-file-lines"></i>       
      &nbsp; <input type="checkbox" /> <a href = "https://www.rossmanchance.com/applets/2021/descstats/Dotplot.htm" target="_blank"><i aria-hidden="true" title="External Link to the Applet"></i> Guided Activity </a>&nbsp; <i class="fas fa-comments"></i>    
    </td>
    <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercise 2.3.3 and Exercise 2.3.10  
<br>
<i class="fas fa-clock"></i><b> DUE DATE: Sun, Jan 21 </b>
    </td>
  </tr>

</table>

### {{< fa calendar-days >}} Week 3 (Jan 22 - Jan 25)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 35%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

  <tr>
    <td> 
    &nbsp; <b> Probability and the Life Sciences </b>  
    &nbsp;<input type="checkbox"> <b>Section 2.6:</b> Measures of Dispersion <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b>Section 3.1:</b> Probability and the Life Sciences <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b>Section 3.2:</b> Introduction to Probability <b>(only pp.83-85)</b><i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016)
    </td>
    <td> 
    &nbsp;<input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/03-Week-03/01-Lecture-01/01-Week-03-Lec-01.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Spread of a Distribution & Introduction to Probability </a>&nbsp; <i class="fas fa-file-lines"></i> 
    </td>
    <td>
    &nbsp;<input type="checkbox"> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercise 2.6.2 and Exercise 2.6.8 <br>     
    &nbsp;<i class="fas fa-clock"></i><b> DUE DATE: Sun, Jan 28 </b>
  </td>
</tr>

  <tr>
    <td> 
    &nbsp; <b> CH 4: The Normal Distribution </b>  
    &nbsp;<input type="checkbox" /> <b>Section 4.1:</b> Introduction <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox" /> <b>Section 4.2:</b> The Normal Curves <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox" /> <b>Section 4.3:</b> Areas under a Normal Curve <i class="fas fa-book-open"></i>   
    &nbsp; FROM Samuels et al. (2016)
</td>
    <td>    
    &nbsp; <input type="checkbox" /> Review 2 - Quiz (On Canvas)</a> &nbsp; <i class="fas fa-highlighter"></i>   
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/03-Week-03/02-Lecture-02/01-Week-03-Lec-02.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Introduction to the Normal Distribution </a>&nbsp; <i class="fas fa-file-lines"></i> 
    </td>
    <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercise 4.3.5    
<br>
<i class="fas fa-clock"></i>  <b> DUE DATE: Sun, Jan 28 </b>
</td>
  </tr>

  <tr>
    <td>
    &nbsp; <b> Ch 2: Description of Samples and Populations </b>  
    &nbsp;<input type="checkbox" /> <b>Section 2.3:</b> Descriptive Statistics <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox" /> <b>Section 2.5:</b> Relationship between Variables <i class="fas fa-book-open"></i>   
    &nbsp;&nbsp;FROM Samuels et al. (2016)</td>
    <td>
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/03-Week-03/03-Lecture-03/03-Week-03-Lec-03-Lab02.html#/title-slide" target="_blank"><i aria-hidden="true" title="External Link to Lab Slides"></i> Lab Slides - Descriptive Statistics </a> &nbsp;<i class="fas fa-file-lines"></i>      
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 2 (GROUP)  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Jan 28 </b>
    </td>
  </tr>

  <tr>
    <td>
      &nbsp; <b> CH 4: The Normal Distribution </b>  
      &nbsp;<input type="checkbox" /> <b>Section 4.4:</b> Assessing Normality <i class="fas fa-book-open"></i>  
      &nbsp;<input type="checkbox" /> <b>Section 4.5:</b> Perspective <i class="fas fa-book-open"></i>    
    </td>
    <td>    
&nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/03-Week-03/04-Lecture-04/01-Week-03-Lec-04.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Assessing Normality </a>&nbsp; <i class="fas fa-file-lines"></i>     
    </td>
    <td> 
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercises 4.4.4 and 4.4.8  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Jan 28 </b>
    </td>
  </tr>
</table>

### {{< fa calendar-days >}} Week 4 (Jan 29 - Feb 1)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 33%">DURING CLASS</th>
    <th style="width: 27%">AFTER CLASS</th>
  </thead>

  <tr>
    <td> 
    &nbsp; <b> Ch 5: Sampling Distribution </b>  
    &nbsp;<input type="checkbox"> <b>Section 5.1:</b> Basic Ideas <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b>Section 5.2:</b> The Sample Mean <i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016)
    </td>
    <td> 
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/04-Week-04/01-Lecture-01/01-Week-04-Lec-01.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lec. Slides - Sampling Distribution </a>&nbsp; <i class="fas fa-file-lines"></i>     
    </td>
    <td>
    &nbsp;<input type="checkbox"> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercise 5.2.8 <br>     
    &nbsp;<i class="fas fa-clock"></i><b> DUE DATE: Sun, Feb 4 </b>
  </td>
</tr>

  <tr>
    <td> 
    &nbsp; <b> Ch 6: Confidence Interval </b>  
    &nbsp;<input type="checkbox" /> <b>Section 6.1:</b> Statistical Estimation <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox" /> <b>Section 6.2:</b> Standard Error of the Mean <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox" /> <b>Section 6.3:</b> Section 6.3: Confidence Interval for µ <i class="fas fa-book-open"></i>
    &nbsp; FROM Samuels et al. (2016)
</td>
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/04-Week-04/02-Lecture-02/01-Week-04-Lecture-02.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lec. Slides - Statistical Estimation & Confidence Interval </a>&nbsp; <i class="fas fa-file-lines"></i>   
    &nbsp; <input type="checkbox" /><a href = "https://canvas.calpoly.edu" target="_blank"><i aria-hidden="true" title="External Link to Survey"></i> Course Check-in Survey (On Canvas)</a> &nbsp; <i class="fas fa-highlighter"></i>
    </td>
    <td>
    &nbsp; NO ASSIGNMENT
</td>
  </tr>

  <tr>
    <td>
    &nbsp; <b> Ch 2: Description of Samples and Populations </b>  
    &nbsp;<input type="checkbox" /> <b>Section 2.5:</b> Relationship between Variables <i class="fas fa-book-open"></i>   
    &nbsp;&nbsp;FROM Samuels et al. (2016)</td>
    <td>
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/04-Week-04/03-Lec-03-Lab-03/03-Lecture-03-Lab-02.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lab Slides - Data Visualization </a>&nbsp; <i class="fas fa-file-lines"></i>   
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1QSDN7AEYnIGyRNYigaSaYkj30WLJT8rY/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lab Worksheet - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 3 (GROUP)  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Feb 11 </b>
    </td>
  </tr>

  <tr>
    <td>
      &nbsp; <b> CH 1 - CH 4: Review All Course Materials </b>  
    </td>
    <td>    
    &nbsp; <input type="checkbox" /> Midterm Review (On Canvas)</a> &nbsp; <i class="fas fa-highlighter"></i>    
    </td>
    <td> 
    &nbsp; NO ASSIGNMENT
    </td>
  </tr>

</table>

### {{< fa calendar-days >}} Week 5 (Feb 5 - Feb 8)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 35%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

<tr>
  <td colspan="3" style="text-align: center;">&nbsp; <b> Midterm 1 (In-class) </b></td>
</tr>

  <tr>
    <td> 
    &nbsp; <b> Ch 6: Confidence Interval </b>  
    &nbsp;<input type="checkbox" /> <b>Section 6.3:</b> CI for µ <i class="fas fa-book-open"></i>    
    &nbsp;<input type="checkbox" /> <b>Section 6.4:</b> Planning a Study to Estimate µ <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox" /> <b>Section 6.5:</b> Conditions for Validity of Estimation Methods <i class="fas fa-book-open"></i>    
    &nbsp; FROM Samuels et al. (2016)
    </td>
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/05-Week-05/02-Lecture-02/01-Week-05-Lecture-02.html"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Student's $t$ Distribution </a>&nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    
  <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercises 6.4.1  
<br>
<i class="fas fa-clock"></i>  <b> DUE DATE: Sun, Feb 11 </b>
</td>
  </tr>

  <tr>
  <td> 
  &nbsp; <b> Ch 6: Confidence Interval </b>    
  &nbsp;<input type="checkbox" /> <b>Section 6.6:</b> Comparing two means <i class="fas fa-book-open"></i>    
  &nbsp;<input type="checkbox" /> <b>Section 6.7:</b> Confidence Interval for µ1 - µ2 <i class="fas fa-book-open"></i>  
  </td>
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/05-Week-05/03-Lecture-03/03-Week-05-Lecture-03.html"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Comparing Two Means </a> &nbsp; <i class="fas fa-file-lines"></i>       
    <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercise 6.7.11   
<br>
<i class="fas fa-clock"></i>  <b> DUE DATE: Sun, Feb 11 </b>
</td>
  </tr>

  <tr>
    <td> &nbsp; <b> Ch 7: Comparison of Two Independent Samples </b>  
    &nbsp;<input type="checkbox" /> The Entire Chapter 7 EXCEPT for Section 7.10 <i class="fas fa-book-open"></i>    
    &nbsp; FROM Samuels et al. (2016)</td>
    <td>
     &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/05-Week-05/04-Lecture-04/01-Week-05-Lecture-04.html"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Introduction to Hypothesis Testing & Comparison of Independent Samples </a> &nbsp; <i class="fas fa-file-lines"></i>       
    </td>
    <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Exercise 7.2.9  
<br>
<i class="fas fa-clock"></i><b> DUE DATE: Sun, Feb 11 </b>
    </td>
  </tr>

</table>

### {{< fa calendar-days >}} Week 6 (Feb 12 - Feb 15)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 37%">BEFORE CLASS</th>
    <th style="width: 38%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

  <tr>
    <td> 
    &nbsp; <b> Ch 7: Inference for Numerical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i> 7.1.5 One sample t-tests</a>&nbsp; <i class="fas fa-book-open"></i>    
    &nbsp; FROM Diez et al. (2022) 
    <br>
    <br>
    &nbsp; <b> Ch 8: Comparison of Paired Samples </b>  
    &nbsp;<input type="checkbox"> <b>Section 8.1:</b> Introduction <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b>Section 8.2:</b> The Paired-Sample t Test and Confidence Interval <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b> Section 8.3:</b> The Paired Design  <i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016)    
    </td>
    <td> 
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/06-Week-06/01-Lecture-01/02-Midterm-Project-Workflow.html"target="_blank"><i aria-hidden="true" title="External Link to Midterm Instructions Slide"></i> Midterm Project Instructions - READ THIS </a> &nbsp; <i class="fas fa-file-lines"></i>   
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/06-Week-06/01-Lecture-01/01-Week-06-Lecture-01.html"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - One sample _t_-tests and paired sample _t_ test </a> &nbsp; <i class="fas fa-file-lines"></i> 
    </td>
    <td>
    &nbsp; NO ASSIGNMENT
  </td>
</tr>

  <tr>
    <td> 
    &nbsp; <b> Chapter 7  & Chapter 8 </b>  
    &nbsp;<input type="checkbox" /> Review your notes of Ch 7 & 8 <i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016)  
    &nbsp; FROM Diez et al. (2022)    
</td>
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://canvas.calpoly.edu/"target="_blank"><i aria-hidden="true" title="External Link to Midterm Instructions Slide"></i> _t_ tests Worksheet (DOWNLOAD or PRINT)(on CANVAS) </a> &nbsp;<i class="fas fa-laptop-file"></i>    
    &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/forms/d/e/1FAIpQLScMqlQh9d49flpfN7H17orKxLzJRCXnc85DuIIk0ZlTpjhWOg/viewform?usp=sf_link"target="_blank"><i aria-hidden="true" title="External Link to Quiz"></i>Ungraded Quiz - Review of _t_ tests </a> &nbsp; <i class="fas fa-link"></i>   
    &nbsp; <input type="checkbox" /><a href = "http://courses.atlas.illinois.edu/spring2016/STAT/STAT200/pt.html"target="_blank"><i aria-hidden="true" title="External Link to p-value calculator"></i>$P$ - value calculator </a> &nbsp; <i class="fas fa-link"></i> 
    </td>
    <td>
    &nbsp; NO ASSIGNMENT
</td>
  </tr>

  <tr>
    <td>
    &nbsp; <b> Chapter 7  & Chapter 8 </b>  
    &nbsp;<input type="checkbox" /> Review your notes of Ch 7 & 8 <i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016)   
    &nbsp; FROM Diez et al. (2022)    
    </td>
    <td>
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1d5c3K64SlwwUZk0DOhlMgi5zVJ6_sSAC/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lab Worksheet - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>  
      &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1p-N8-wNLFabCMmIG4gj5AzMuAn0mt6ts/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Dataset"></i> Lab Dataset - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>      
      &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/06-Week-06/03-Lecture-03/01-Week-06-Lec-03-Lab-04-slide.html"target="_blank"><i aria-hidden="true" title="External Link to Lab Slide"></i> Lab Slides - _t_-tests </a> &nbsp; <i class="fas fa-file-lines"></i> 
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 4 (GROUP)  
     &nbsp; &nbsp; &nbsp; _Upload the lab worksheet we will work on in class._
    <br>
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Feb 18 </b>
    </td>
  </tr>

  <tr>
    <td>
    &nbsp; <b> Review of Ch.7 & Ch.8 </b> &nbsp; <i class="fas fa-book-open"></i>    
    </td>
    <td>    
    &nbsp; <input type="checkbox" /> Lecture Slides & Lab Slides of This Week &nbsp; <i class="fas fa-file-lines"></i>
    </td>
    <td> 
    &nbsp; NO ASSIGNMENT
    </td>
  </tr>

</table>


### {{< fa calendar-days >}} Week 7 (Feb 19 - Feb 22)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 45%">BEFORE CLASS</th>
    <th style="width: 30%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

<tr>
  <td colspan="3" style="text-align: center;">&nbsp; <b>No Class Today !</b></td>
</tr>

  <tr>
    <td>
    &nbsp; <b> Ch 6: Inference for Categorical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sec. 6.1</b> Inference for a single proportion</a>&nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Diez et al. (2022) 
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/07-Week-07/01-Lecture-01/01-Week-07-Lec-01.html"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Inference for a single proportion </a> &nbsp; <i class="fas fa-file-lines"></i> 
    </td>
    <td> 
    &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i>    &nbsp;<a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Homework PDF"></i> <b>Exercise 6.8 (c), (d), (e)</b></a>  
    <br>
    <b>FROM Diez et al. (2022)</b></a> 
    <br>  
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Feb 25 </b>    
    </td>
  </tr>
  <tr>
    <td>
    &nbsp; <b> Ch 6: Inference for Categorical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sec. 6.2</b> Difference of two proportions</a>&nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Diez et al. (2022) 
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/07-Week-07/02-Lecture-02/01-Week-07-Lec-02.html"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Inference for Categorical Data </a> &nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    <td> &nbsp; NO ASSIGNMENT</td>
  </tr>
  <tr>
    <td>
    &nbsp; <b>Ch 6: Inference for Categorical Data</b>  
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sect. 6.3</b> Testing for goodness of fit using chi-square</a>&nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sect. 6.4 </b> Testing for independence in two-way tables</a>&nbsp;<i class="fas fa-book-open"></i>   
    &nbsp;&nbsp;FROM Diez et al. (2022)
    </td>
    <td>
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1ETgrYuwOlq4Q7lkuyZfgeGwLwpAWXrPU/view?usp=drive_link" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lab Worksheet - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>  
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/07-Week-07/03-Lecture-03/01-Presentation/01-Week-07-Lec-01-Lab-06.html" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide"></i> Lab Slides - Chi-square tests </a> &nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 5 (GROUP)  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Feb 25 </b>
    </td>
  </tr>

</table>

### {{< fa calendar-days >}} Week 8 (Feb 26 - Feb 29)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 35%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

<tr>
    <td>
    &nbsp; <b> Ch 6: Inference for Categorical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i> Chapter Review </a>&nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Diez et al. (2022) 
    </td>   
    <td>    
    &nbsp; <input type="checkbox"><a href="https://docs.google.com/presentation/d/1Az39ImioV625MVHn4ng65cxoGJQ1UgUmoGg0RpDhqxI/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Chi-Square Test, Relative Risk and the Odds Ratio </a> &nbsp; <i class="fas fa-file-lines"></i>    
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1qyjwEXDHa6WM_zSNCFJYg3Hxf3fX54zj/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lecture Worksheet - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>      
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Take-Home Midterm   
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Fri, Feb 29 </b>
    </td> 
</tr>
  <tr>
    <td>
    &nbsp; Comprehensive Review of Weeks 1-7
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /> <a href = "https://forms.gle/EhNufakn5hQ3rDbd7" target="_blank"><i aria-hidden="true" title="External Link to Quiz"></i> Review Quiz (UNGRADED) </a>&nbsp; &nbsp; <i class="fas fa-highlighter"></i> 
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Take-Home Midterm   
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Fri, Feb 29 </b>
    </td> 
    </tr>
  <tr>
    <td>
    &nbsp; <b> Ch 12: Linear Regression and Correlation </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 12.2</b> The Correlation Coefficient &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox"><a href="https://docs.google.com/presentation/d/1WsUt32g2uXoUDCUqEirjiSQFhSXoyrdqi2QOeRQepBw/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Correlation </a> &nbsp; <i class="fas fa-file-lines"></i>    
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1L9hLmC7hMHUcaMBrERRtJ0dUVUiPDjr3/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lecture Worksheet - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>     
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Take-Home Midterm   
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Fri, Feb 29 </b>
    </td> 
    </tr>
  <tr>
    <td> &nbsp; <b> Midterm Project Topics </b></td>
    <td> &nbsp;<input type="checkbox">In-Class Q&A: Take-Home Midterm Topics &nbsp; <i class=""fas fa-comments></i></td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Take-Home Midterm   
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Fri, Feb 29 </b>
    </td> 
    </tr>

</table>




### {{< fa calendar-days >}} Week 9 (Mar 4 - Mar 7)


<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 37%">DURING CLASS</th>
    <th style="width: 23%">AFTER CLASS</th>
  </thead>

<tr>
    <td>
    &nbsp; <b> Ch 12: Linear Regression and Correlation </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.3</b> The Fitted Regression Line &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 12.4</b> Parametric Interpretation of Regression: The Linear Model &nbsp; <i class="fas fa-book-open"></i>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.5</b> Statistical Inference Concerning $\beta_1$ &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016) 
    </td>   
    <td>    
    &nbsp; <input type="checkbox"><a href="https://docs.google.com/presentation/d/1gB8pkpfn9pbzg_0FH3m0IKFFhPOImE7NkEF_-eSSpfw/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Least Squares Regression </a> &nbsp; <i class="fas fa-file-lines"></i>   
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Week 9 Individual Assignment (on CANVAS)
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Mar 10 </b>
    </td> 
</tr>
  <tr>
    <td>
    &nbsp;<input type="checkbox" />  <b> Ch 12: Linear Regression and Correlation </b>   
    </td>   
    <td>    
   &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1IFgER-Hwpp-uGrGdioWpB34ULv1Tt8XI/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lab Worksheet - Correlation & LSR (DOWNLOAD) </a>&nbsp; <i class="fas fa-laptop-file"></i>  
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/09-Week-09/02-Lecture-02/01-Presentation/01-Lec-02-Lab-07.html" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide"></i> Lab Slides - Correlation & LSR </a> &nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 6  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Mar 10 </b>
    </td> 
    </tr>
  <tr>
    <td>
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.2</b> The Basic One-Way ANOVA &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.4</b> The Global F Test &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.5</b> Applicability of Methods &nbsp; <i class="fas fa-book-open"></i> 
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
   &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/16o-ZKL6qHJHDh9YPzEYhsE-Rf10dlyLg/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lecture Worksheet (DOWNLOAD) </a>&nbsp; <i class="fas fa-laptop-file"></i>  
    &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/presentation/d/1v4ILGcE91NofW7E7LYMlZ_-oySQSfnnUlsmGDELAkz4/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - One-Way ANOVA</a> &nbsp; <i class="fas fa-file-lines"></i>       
    </td>
    <td>
     &nbsp; NO ASSIGNMENT 
    </td> 
    </tr>
  <tr>
    <td>     
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.2</b> The Basic One-Way ANOVA &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.4</b> The Global F Test &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.5</b> Applicability of Methods &nbsp; <i class="fas fa-book-open"></i> 
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1n9xMg0aeU1H0mJl0P2RdX2xoTQzXo_Uk/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lab Worksheet - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>  
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1on3iwpmV0c1zJrdOY4C9H1QwNISPsix8/view?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Dataset"></i> Lab Dataset - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>      
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/09-Week-09/04-Lecture-04/01-Presentation/01-Week-09-Lec-04-Lab-08.html"target="_blank"><i aria-hidden="true" title="External Link to Lab Slide"></i> Lab Slides - One-Way ANOVA </a> &nbsp; <i class="fas fa-file-lines"></i>     
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 6  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Mar 10 </b>    </td> 
    </tr>

</table>

### {{< fa calendar-days >}} Week 10 (Mar 11 - Mar 14)


<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 43%">BEFORE CLASS</th>
    <th style="width: 32%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

<tr>
    <td>
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.6</b> One-Way Randomized Blocks Design &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.7</b> Two-Way ANOVA &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/10-Week-10/01-Lecture-01/01-Lecture-01.html"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Randomized Blocks Design & Two-Way ANOVA </a> &nbsp; <i class="fas fa-file-lines"></i>       
    </td>
    <td>
     &nbsp; NO ASSIGNMENT 
    </td> 
</tr>
  <tr>
    <td>
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.9</b> Multiple Comparisons &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://stat218-wi24.github.io/slides/10-Week-10/02-Lecture-02/01-Lec-02-Lab-09.html"target="_blank"><i aria-hidden="true" title="External Link to Lab Slide"></i> Lab Slides - Two-Way ANOVA </a> &nbsp; <i class="fas fa-file-lines"></i>       
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1upuhTGNyedbt_BmidVm4GGazqjiNRpNb/view?usp=drive_link" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lab Worksheet - DOWNLOAD </a>&nbsp; <i class="fas fa-laptop-file"></i>   
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 7  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Mar 17 </b>    </td> 
    </tr>
  <tr>
    <td>
    &nbsp;<input type="checkbox" /><b> All chapters given above </b>    
    <br>
    &nbsp; FROM Samuels et al. (2016) & FROM Diez et al. (2022) 
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox"> Mock Final (On CANVAS)</a> &nbsp; <i class="fas fa-highlighter"></i>   
    </td>
    <td> 
    &nbsp; NO ASSIGNMENT 
    </td> 
    </tr>
  <tr>
    <td> &nbsp; <b> Final Project Topics </b></td>
    <td> &nbsp;<input type="checkbox">In-Class Q&A: Take-Home Final Topics &nbsp; <i class=""fas fa-comments></i></td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Take-Home Final   
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Tue, Mar 19 </b>
    </td> 
    </tr>

</table>